# -*- coding: utf-8 -*-
"""The two ways of working, inserted after the chapter on creating a roof
project, in each language."""

FLOWS = {
"nl": ("Twee werkwijzen", [
    ("p", "Tectora werkt op twee manieren. Beide eindigen in hetzelfde project met dezelfde planning; het verschil is of de offerte uit een sjabloon of uit de tekening komt."),
    ("h2", "Flow 1 — CRM → Offerte → Order → Project → Planning"),
    ("p", "Voor snelle offertes zonder tekening, bijvoorbeeld een herstelling of een dak met gekende maten."),
    ("ol", [
        "<b>CRM</b>: maak of open de opportuniteit. Vul klant en werfadres in.",
        "<b>Offerte</b>: klik <b>Nieuwe offerte</b> op de opportuniteit en kies een <b>offertesjabloon</b> (Renovatie of Nieuwbouw). Bij het opslaan ontstaat automatisch het dakproject; de sjabloonlijnen verschijnen in de hoofdstuktabs. Pas de hoeveelheden aan op de offerte of op het dakproject: getelde producten volgen wat u invult.",
        "<b>Order</b>: stuur de offerte, laat ze ondertekenen en klik <b>Bevestigen</b>. Het dakproject gaat naar Order bevestigd en de materiaallijst wordt opgebouwd.",
        "<b>Project</b>: het planbare project ontstaat automatisch (klant — gemeente). Open het dashboard via de smart button <b>Projectdashboard</b>.",
        "<b>Planning</b>: kies op het dakproject de ploeg en de geplande periode. Het werkblok en de shifts van de ploegleden verschijnen in de Planning-app.",
    ]),
    ("h2", "Flow 2 — CRM → Dakplan → Offerte/Order → Project → Planning"),
    ("p", "Voor werven die u opmeet: de tekening voedt de offerte en elke wijziging aan het plan volgt door tot op de order."),
    ("ol", [
        "<b>CRM</b>: klik op de opportuniteit <b>Dakproject maken</b>. Klant en adres worden overgenomen.",
        "<b>Dakplan</b>: sla het dakproject op, haal het satellietbeeld op, teken het dak over en schaal het (zie best practice hieronder). Wijs producten toe via de labels; vink de algemene werken en veiligheidsvoorzieningen aan.",
        "<b>Offerte/Order</b>: klik <b>Offerte maken</b>. De offerte krijgt een kop per daksectie met de gemeten hoeveelheden. Wijzigt het plan nog, dan volgt de offerte automatisch; met <b>Offerte bijwerken uit meting</b> dwingt u dat af. Bevestig de order.",
        "<b>Project</b>: het project ontstaat bij bevestiging; het dashboard toont de meting op de tab Dakmeting.",
        "<b>Planning</b>: ploeg en periode op het dakproject → werkblok → shifts in de Planning-app.",
    ]),
    ("h2", "Best practice: satellietbeeld opladen, dak overtekenen en schalen op één zijde"),
    ("ol", [
        "Vul het <b>werfadres</b> volledig in (straat, nummer, postcode, gemeente) en sla het dakproject op.",
        "Klik op de tab Tekening op het <b>wereldbol-icoon → Satellietbeeld ophalen</b>. De foto verschijnt als achtergrond en de schaal wordt uit de kaartprojectie afgeleid.",
        "Zet de transparantie zo dat de dakranden goed zichtbaar zijn en zoom in op het dak (scrollen, of F voor volledig scherm).",
        "<b>Teken het dak over</b>: gebruik Polygoon en klik elke hoek van het dakvlak op de foto; sluit met dubbelklik. Teken elk apart dakvlak als eigen sectie en zet een <b>naad</b> waar twee vlakken elkaar raken.",
        "<b>Meet ter plaatse één zijde</b> die goed herkenbaar is, liefst de langste. Rechtsklik op het lengtelabel van die zijde op de tekening en geef de gemeten lengte in.",
        "De tekening wordt <b>automatisch herschaald</b>: alle andere zijden, oppervlaktes en omtrekken worden herrekend, en de offertehoeveelheden volgen. Controleer één tweede zijde als steekproef.",
        "Voeg schoorstenen en koepels toe met rechtsklik, stel per zijde randbreedte en opstand in en wijs de producten toe.",
    ]),
    ("tip", "Zonder satellietbeeld werkt dezelfde methode met een geüpload plan of een foto: overtekenen, één zijde meten, rechtsklik, klaar."),
]),
"en": ("Two ways of working", [
    ("p", "Tectora works in two ways. Both end in the same project with the same planning; the difference is whether the quotation comes from a template or from the drawing."),
    ("h2", "Flow 1 — CRM → Quotation → Order → Project → Planning"),
    ("p", "For quick quotations without a drawing, such as a repair or a roof with known dimensions."),
    ("ol", [
        "<b>CRM</b>: create or open the opportunity. Fill in customer and site address.",
        "<b>Quotation</b>: click <b>New quotation</b> on the opportunity and pick a <b>quotation template</b> (Renovatie or Nieuwbouw). On save the roof project is created automatically; the template lines appear in the chapter tabs. Adjust quantities on the quotation or on the roof project: counted products follow what you enter.",
        "<b>Order</b>: send the quotation, have it signed and click <b>Confirm</b>. The roof project moves to Order bevestigd and the material list is built.",
        "<b>Project</b>: the plannable project is created automatically (customer — municipality). Open the dashboard through the <b>Projectdashboard</b> smart button.",
        "<b>Planning</b>: on the roof project pick the team and the planned period. The work block and the team members' shifts appear in the Planning app.",
    ]),
    ("h2", "Flow 2 — CRM → Roof plan → Quotation/Order → Project → Planning"),
    ("p", "For sites you measure: the drawing feeds the quotation and every change to the plan follows through to the order."),
    ("ol", [
        "<b>CRM</b>: on the opportunity click <b>Dakproject maken</b>. Customer and address are taken over.",
        "<b>Roof plan</b>: save the roof project, fetch the satellite image, trace the roof and scale it (see the best practice below). Assign products through the labels; tick the general works and safety measures.",
        "<b>Quotation/Order</b>: click <b>Offerte maken</b>. The quotation gets a header per roof section with the measured quantities. If the plan still changes, the quotation follows automatically; <b>Offerte bijwerken uit meting</b> forces it. Confirm the order.",
        "<b>Project</b>: the project is created on confirmation; the dashboard shows the measurement on the Dakmeting tab.",
        "<b>Planning</b>: team and period on the roof project → work block → shifts in the Planning app.",
    ]),
    ("h2", "Best practice: load the satellite image, trace the roof and scale on one side"),
    ("ol", [
        "Fill in the <b>site address</b> completely (street, number, postcode, municipality) and save the roof project.",
        "On the Tekening tab click the <b>globe icon → Satellietbeeld ophalen</b>. The photo appears as background and the scale is derived from the map projection.",
        "Set the transparency so the roof edges are clearly visible and zoom in on the roof (scroll, or F for full screen).",
        "<b>Trace the roof</b>: use Polygoon and click every corner of the roof surface on the photo; close with a double-click. Draw each separate roof surface as its own section and put a <b>seam</b> where two surfaces meet.",
        "<b>Measure one side on site</b> that is easy to recognise, preferably the longest. Right-click the length label of that side on the drawing and enter the measured length.",
        "The drawing is <b>rescaled automatically</b>: all other sides, areas and perimeters are recomputed and the quotation quantities follow. Check a second side as a spot check.",
        "Add chimneys and domes with a right-click, set edge width and upstand per side and assign the products.",
    ]),
    ("tip", "Without a satellite image the same method works with an uploaded plan or photo: trace, measure one side, right-click, done."),
]),
"sq": ("Dy mënyra pune", [
    ("p", "Tectora punon në dy mënyra. Të dyja përfundojnë në të njëjtin projekt me të njëjtin planifikim; dallimi është nëse oferta vjen nga një model ose nga vizatimi."),
    ("h2", "Rrjedha 1 — CRM → Ofertë → Porosi → Projekt → Planifikim"),
    ("p", "Për oferta të shpejta pa vizatim, për shembull një riparim ose një çati me përmasa të njohura."),
    ("ol", [
        "<b>CRM</b>: krijoni ose hapni mundësinë e shitjes. Plotësoni klientin dhe adresën e kantierit.",
        "<b>Oferta</b>: klikoni <b>Ofertë e re</b> në mundësinë e shitjes dhe zgjidhni një <b>model oferte</b> (Renovatie ose Nieuwbouw). Me ruajtjen krijohet automatikisht projekti i çatisë; rreshtat e modelit shfaqen në skedat e kapitujve. Rregulloni sasitë në ofertë ose në projektin e çatisë: produktet e numëruara ndjekin çfarë vendosni ju.",
        "<b>Porosia</b>: dërgoni ofertën, merrni nënshkrimin dhe klikoni <b>Konfirmo</b>. Projekti i çatisë kalon në Order bevestigd dhe ndërtohet lista e materialeve.",
        "<b>Projekti</b>: projekti i planifikueshëm krijohet automatikisht (klienti — komuna). Hapni panelin përmes butonit <b>Projectdashboard</b>.",
        "<b>Planifikimi</b>: në projektin e çatisë zgjidhni ekipin dhe periudhën e planifikuar. Blloku i punës dhe turnet e anëtarëve të ekipit shfaqen në aplikacionin Planning.",
    ]),
    ("h2", "Rrjedha 2 — CRM → Plani i çatisë → Ofertë/Porosi → Projekt → Planifikim"),
    ("p", "Për kantiere që i matni vetë: vizatimi ushqen ofertën dhe çdo ndryshim në plan ndiqet deri te porosia."),
    ("ol", [
        "<b>CRM</b>: në mundësinë e shitjes klikoni <b>Dakproject maken</b>. Klienti dhe adresa merren automatikisht.",
        "<b>Plani i çatisë</b>: ruani projektin e çatisë, merrni imazhin satelitor, vizatoni çatinë sipër fotos dhe kalibroni shkallën (shihni praktikën më të mirë më poshtë). Caktoni produktet përmes etiketave; shënoni punimet e përgjithshme dhe masat e sigurisë.",
        "<b>Oferta/Porosia</b>: klikoni <b>Offerte maken</b>. Oferta merr një titull për çdo seksion çatie me sasitë e matura. Nëse plani ndryshon ende, oferta ndjek automatikisht; <b>Offerte bijwerken uit meting</b> e detyron. Konfirmoni porosinë.",
        "<b>Projekti</b>: projekti krijohet me konfirmimin; paneli tregon matjen në skedën Dakmeting.",
        "<b>Planifikimi</b>: ekipi dhe periudha në projektin e çatisë → bllok pune → turne në aplikacionin Planning.",
    ]),
    ("h2", "Praktika më e mirë: ngarkoni imazhin satelitor, vizatoni çatinë sipër dhe kalibroni me një anë"),
    ("ol", [
        "Plotësoni <b>adresën e kantierit</b> plotësisht (rruga, numri, kodi postar, komuna) dhe ruani projektin e çatisë.",
        "Në skedën Tekening klikoni <b>ikonën e globit → Satellietbeeld ophalen</b>. Fotoja shfaqet si sfond dhe shkalla nxirret nga projeksioni i hartës.",
        "Vendosni tejdukshmërinë që skajet e çatisë të duken qartë dhe zmadhoni çatinë (rrotulloni, ose F për ekran të plotë).",
        "<b>Vizatoni çatinë sipër fotos</b>: përdorni Polygoon dhe klikoni çdo qoshe të sipërfaqes së çatisë; mbyllni me dopio-klik. Vizatoni çdo sipërfaqe të veçantë si seksion më vete dhe vendosni një <b>bashkim</b> ku dy sipërfaqe takohen.",
        "<b>Matni në vend një anë</b> që njihet lehtë, mundësisht më të gjatën. Klikoni me të djathtën etiketën e gjatësisë së asaj ane në vizatim dhe vendosni gjatësinë e matur.",
        "Vizatimi <b>rikalibrohet automatikisht</b>: të gjitha anët, sipërfaqet dhe perimetrat e tjera rillogariten dhe sasitë e ofertës ndjekin. Kontrolloni një anë të dytë si provë.",
        "Shtoni oxhaqe dhe kupola me klik të djathtë, vendosni gjerësinë e skajit dhe ngritjen për çdo anë dhe caktoni produktet.",
    ]),
    ("tip", "Pa imazh satelitor e njëjta metodë funksionon me një plan ose foto të ngarkuar: vizatoni sipër, matni një anë, klik i djathtë, gati."),
]),
}
