# -*- coding: utf-8 -*-
{
    "name": "Data Forge Productcatalogus",
    "summary": "Leverancierscatalogus: producten, prijzen, leveranciers en "
    "categorieën voor de dakwerken",
    "description": """
Data Forge Productcatalogus
===========================
Seeds the product database from the company's supplier catalogue export
(``producten_Tectora_BV_<date>.xlsx``, 1497 products):

* products classified into the existing category tree — works categories are
  reused as-is, material families become sub-categories of "04. Opbouwwerken
  plat dak" — using the export's product group, then name keywords, then the
  supplier's (homogeneous) assortment;
* purchase price as cost, sales price from the export, or cost x 1.85 (the
  catalogue's own median markup) where no sales price is given — those are
  tagged "Prijs berekend";
* vendors created as partners with a vendor pricelist line per product,
  carrying the purchase price and the vendor's product code;
* units normalised to Stuk / m / m² / kg / Uur / Dag / Forfait, packaging
  information kept in the description, unique EANs stored as barcodes;
* products with a supplier are storable purchasables, products without one are
  the price book's works items and become services;
* the two are kept apart in the category tree: the chapters hold the works
  items, which can be sold, and the same chapter structure under a
  "Grondstoffen" branch holds the materials, which cannot. The drawing's
  product picker whitelists per category, so a material never turns up in a
  quotation by accident.

The data lives in ``data/product_catalog.json``, generated by
``tools/parse_product_export.py``. The import runs on module install and can
be re-run via ``env["product.template"]._tectora_import_product_catalog()``;
it is idempotent (matched on the supplier product code) and archives the
previous price-book products (``DAK-*``) instead of deleting them.

The earlier works price book stays available through
``_tectora_import_price_book()`` and the Renovatie / Nieuwbouw / Industrie
pricelists.

Twenty quotation templates (``sale.order.template``) are built on the same
catalogue: ten for a renovation, with the demolition works, and ten for new
construction, without. All of them open with the general works and the
mandatory safety measures and carry a roof build-up of vapour barrier, one
insulation and one membrane, a roof edge with the inner and outer corners that
belong to that very profile, and the rainwater drainage; a dome, a roof window,
scaffolding and a lift are offered as optional lines. The quantities describe a
reference roof of 100 m² with 40 lm of edge, one inner and four outer corners
and two outlets, and are overwritten by the measurement -- the drawing feeds
the quotation. The data lives in ``data/quotation_templates.json``, generated
and validated by ``tools/build_quotation_templates.py``; loading is idempotent
and never overwrites the lines of a template the office has already tuned.
    """,
    "version": "19.0.2.4.0",
    "category": "Sales",
    "license": "Other proprietary",
    "author": "Data Forge",
    "website": "https://www.data-forge.be",
    "depends": ["product", "sale_management"],
    "external_dependencies": {"python": ["openpyxl"]},
    "data": [
        "security/ir.model.access.csv",
        "wizard/product_catalog_import_views.xml",
        "wizard/quotation_template_import_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
}
